### ISSUE TITLE
[BUG] Could not load settings .options when start chia-repl

### ISSUE THREAD

**Issue by kimsk** [dkackman/chia-repl#14]
When I start the `chia-repl`, I get the error messages, but the `repl` still runs.
```sh
❯ node --version
v14.17.4
❯ npm --version
7.20.3
❯ chia-repl
Could not load settings .options
Error: ENOENT: no such file or directory, open '/home/karlkim/.chia-repl/.options'
🌿 Could not load settings .lastConnectionName
Error: ENOENT: no such file or directory, open '/home/karlkim/.chia-repl/.lastConnectionName'
Could not load settings .connection
Error: ENOENT: no such file or directory, open '/home/karlkim/.chia-repl/.connection'
Connection prefix not set. Setting to "xch". Double check the connection's properties and .save-connection.
Welcome to Chia!
Type .help or .more-help to get started
🌿 .version
0.11.1
```

- OS: **WSL Ubuntu 20.04**
- Version **0.11.1**
- Chia version **1.4.0**

**Comment by dkackman** [comment]
The latest code in main has a fox for this. And it is indeed not fatal. Will push a new package soon.

**Comment by kimsk** [comment]
That works great. Thanks! Feel free to close once the npm package is updated.
![image](https://user-images.githubusercontent.com/116863/178400125-9a58b204-679d-4908-858b-b5a1d13342a3.png)

**Comment by kimsk** [comment]
I reinstall the npm module and it works as expected now. Thanks!

**Comment by dkackman** [comment]
This fix is published in https://www.npmjs.com/package/chia-repl/v/0.11.3
